name: Jekyll Writer
description: Simple blogging site
author: mjohnq3
title: Jekyll Writer

url: mjohnq3.github.io
baseurl: /jekyll-writer

gems:
  - jekyll-time-to-read
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: :compressed

markdown: rdiscount
rdiscount:
  extensions:
    - autolink
    - footnotes
    - smart

permalink: /blog/:year/:month/:day/:title/
highlighter: pygments

paginate: 3

google_analytics_tracking_id: xxx # your GA ID


