name: Jekyll Writer
description: Simple blogging site
author: mjohnq3
title: Jekyll Writer

url: mjohnq3.github.io/jekyll-writer
baseurl: /jekyll-writer

gems:
  - jekyll-time-to-read
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: :expanded

markdown: rdiscount
permalink: /blog/:year/:month/:day/:title/
highlighter: pygments

paginate: 3


